### ISSUE TITLE
Connection Documentation

### ISSUE THREAD

**Issue by grgaortiz** [mekterovic/jqOlapCube#1]
I love this, been looking for an OLAP browser for a while. I'd love to help contribute. We build cubes internally and have always wanted a web-based browser for them. The documentation doesn't cover how the connection works. Can you shed some light on that? We have a SSAS running. Also, how does the MDX get generated or does work differently?

**Comment by mekterovic** [comment]
Great, I'll send you an email directly and we can get started! :)

**Comment by mekterovic** [comment]
George,

That's great, I'm glad you're willing to contribute, I already have some tasks for you ☺.

First, let me explain the current state of the affairs.


-          I work at the University in Zagreb, CS department of Faculty of el.engineering and computing and teach BI and some other stuff

-          However, I have developed jqOlapCube for commercial (state) project, but I’ve required, at least for that part of the project, that the jqOlapCube be FLOSS, and it is, and that’s great

-          I’ve released it as jqCube, only to realize later that that name is not unique and have decided to rebrand it as jqOlapCube

-          A student of mine did his master thesis and I’ve employed him to add visualizations using D3 (it actually analyses the dataset retrieved and suggests appropriate chart types)

-          So, now a half-polished version (I believe that student’s code has a few esthetic glitches) is deployed at github

And then, of course, I had to do other things and would love if someone would help.

What remains to be done it so:

·         Check it once again, maybe polish out some things, make it prettier (you’ll notice that e.g. chart icons are a bit ugly)

·         Finish the docs (wiki) – good news is that I have a basic docs in pdf (see attachment)

·         Advertise it! Most notably, we should register the plugin at jQuery’s page!

Would you be willing to do some of these things?


Best,

Igor Mekterović

BTW, you can checkout the previous version (without charts) on this link: http://kent.zpr.fer.hr/igordev/olapservice/index.html
(please don’t spread it around, the server is a bit sluggish)
Yes, this is MSAS running in the background with the good old AdventureWorks DB.

MDX gets generated in the client (browser), you can see the actual MDX going “over the wire” if you start dev tools and monitor ajax network requests, you can do that on this link above as well.
Also, here is the demo student made: https://www.youtube.com/watch?v=3VRJ3tdQ1CQ   showing charts capability.

**Comment by mekterovic** [comment]
Hi George, that's great news, can you please send me you email to igor.mekterovic@fer.hr and I'll bring you up to speed.

**Comment by mekterovic** [comment]
Oh, and I've updated the wiki...
